---
name: MakePluginPlus
main: kim\present\makepluginplus\MakePluginPlus
version: 1.0.0
api: [3.0.0, 4.0.0]
author: PresentKim
description: 소스 플러그인 자동 빌드 플러그인
depend: ['DevTools']

permissions:
  makepluginplus.cmd:
    description: MakePluginPlus main command
    default: op
...
